# Generated by Django 3.2 on 2023-05-25 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bid', models.DecimalField(decimal_places=2, max_digits=50)),
            ],
            options={
                'db_table': 'bidder',
                'ordering': ['bid'],
            },
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=50)),
                ('increment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('auction_date', models.DateTimeField()),
                ('sold', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Lots',
                'db_table': 'lot',
            },
        ),
        migrations.CreateModel(
            name='LotImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='property')),
                ('image_url', models.URLField(editable=False, max_length=2048)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.lot')),
            ],
            options={
                'verbose_name_plural': 'Lot Images',
            },
        ),
        migrations.AddIndex(
            model_name='lot',
            index=models.Index(fields=['name', 'price', 'increment'], name='lot_name_7b4e5d_idx'),
        ),
        migrations.AddField(
            model_name='bid',
            name='bidder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bid',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.lot'),
        ),
        migrations.AddIndex(
            model_name='lotimage',
            index=models.Index(fields=['image_url'], name='img_idx'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['bidder', 'bid'], name='bid_idx'),
        ),
    ]
