# Generated by Django 3.2 on 2023-05-25 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotimage',
            name='image_url',
            field=models.URLField(blank=True, editable=False, max_length=2048),
        ),
    ]
