# Generated by Django 3.2 on 2023-07-04 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0007_alter_lot_buyer'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='lotimage',
            name='img_idx',
        ),
        migrations.RemoveField(
            model_name='lotimage',
            name='image_url',
        ),
        migrations.AlterField(
            model_name='lotimage',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AddIndex(
            model_name='lotimage',
            index=models.Index(fields=['image'], name='img_idx'),
        ),
    ]
